name: 001_Create_Branch_From_Upstream

on:
  workflow_dispatch:
    inputs:
      upstream:
        description: 'Repo of upstream:'
        required: true
        default: 'kkgit2008/AndroIDE'
      upstream_branch:
        description: 'Branch of upstream(required):'
        required: true
        default: 'main'
      new_branch:
        description: 'New branch name:'
        required: true
        default: 'new-branch'
      set_default:
        description: 'Set as default branch?'
        type: boolean
        required: false
        default: false

jobs:
  fork-create:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          # Get Full Commit History To Prevent Error Of shallow
          fetch-depth: 0

      - name: Configure Git Authentication
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Add remote Of Upstream And Pull Branch
        run: |
          git remote add upstream https://github.com/${{ inputs.upstream }}.git
          git fetch upstream ${{ inputs.upstream_branch }}:${{ inputs.new_branch }}

      - name: Push New Branch To Repo
        run: |
          git push -u origin ${{ inputs.new_branch }}

      - name: Set As Default Branch If Needed
        if: inputs.set_default
        run: |
          gh api repos/${{ github.repository }} \
             --method PATCH \
             --field default_branch="${{ inputs.new_branch }}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

