name: 004_pr_to_upstream
on:
  workflow_dispatch:
    inputs:
      head:
        description: Branch in your repo to PR(empty=default)
        required: false
        default: ''
      title:
        description: PR title(empty=auto)
        required: false
        default: ''

jobs:
  create-pr:
    runs-on: ubuntu-latest
    permissions:
      contents: read          # fetch repo info
      pull-requests: write    # open PR in upstream
    steps:
      # check out chosen branch; fallback to default if empty
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.head || github.event.repository.default_branch }}

      # detect upstream repo & default branch, then create PR
      - name: open-pull-request
        run: |
          # detect upstream owner/repo
          UP=$(gh api "${{ github.repository }}" --jq .parent.full_name)
          # detect upstream default branch
          UB=$(gh api "repos/$UP" --jq .default_branch)
          # set head branch
          HB="${{ inputs.head || github.event.repository.default_branch }}"
          # create PR; ignore if duplicate
          gh pr create -R "$UP" -H "${{ github.repository_owner }}:$HB" -B "$UB" \
             -t "${{ inputs.title || 'sync' }}" -b "Auto PR from $HB" || true
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}