name: 004_pr_to_upstream
on:
  workflow_dispatch:
    inputs:
      head:
        description: Branch in your repo to PR
        required: false
        default: ''
      title:
        description: PR title (empty=auto)
        required: false
        default: ''

jobs:
  create-pr:
    runs-on: ubuntu-latest
    permissions:
      contents: read          # need repo info
      pull-requests: write    # create PR in upstream
    steps:
      # checkout the chosen branch; fallback to repo default if input is empty
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.head || github.event.repository.default_branch }}

      # detect upstream repo & its default branch, then open PR
      - name: open-pull-request
        run: |
          # grab upstream owner/repo
          UP=$(gh api "${{ github.repository }}" --jq .parent.full_name)
          # grab upstream default branch
          UB=$(gh api "$UP" --jq .default_branch)
          # decide head branch
          HB="${{ inputs.head || github.event.repository.default_branch }}"
          # create PR; silent success if already exists
          gh pr create -R "$UP" -H "${{ github.repository_owner }}:$HB" -B "$UB" \
             -t "${{ inputs.title || 'sync' }}" -b "Auto PR from $HB" || true
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}