name: 004_pr_to_upstream
on:
  workflow_dispatch:
    inputs:
      upstream:
        description: 'Upstream owner/repo:'
        required: true
        default: 'kkgit2008/AndroIDE'
      head:
        description: 'Branch in your repo to PR:'
        required: false
        default: 'main'
      title:
        description: 'PR title(empty=auto):'
        required: false
        default: ''

jobs:
  create-pr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.head || github.event.repository.default_branch }}

      - name: open-pull-request
        run: |
          # 1. Get upstream repo
          if [ -n "${{ inputs.upstream }}" ]; then
            UP="${{ inputs.upstream }}"
          else
            UP=$(gh api "repos/${{ github.repository }}" --jq .parent.full_name)
            if [ -z "$UP" ]; then
              echo "::error::This repo is not a fork; please input upstream owner/repo manually."
              exit 1
            fi
          fi

          # 2. Get upstream default branch
          UB=$(gh api "repos/$UP" --jq .default_branch)

          # 3. Set HEAD branch
          HB="${{ inputs.head || github.event.repository.default_branch }}"

          # 4. Create PR (skip if duplicate)
          gh pr create -R "$UP" -H "${{ github.repository_owner }}:$HB" -B "$UB" \
             -t "${{ inputs.title || 'sync' }}" -b "Auto PR from $HB" || true
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}