
# ===================================================================
#  Reusable : Can build all ABI/build-type and upload APK + mapping
#  Read file RELEASE_INFO and get params：
#    - VER_NAME          （Required）
#    - TITLE / BRANCH / PRERELEASE / NOTES  (Only read when publish)
# ===================================================================



name: .Reusable Action

on:
  workflow_call:
  
    inputs:
      build_type:
        description: 'debug or release'
        required: true
        type: string
      abi_type:
        description: 'e.g. arm64-v8a'
        required: true
        type: string
      
      # Optional input parameters
      
      override_info_file:
        description: 'path to RELEASE_INFO (repo root relative)'
        required: false
        default: 'RELEASE_INFO'
        type: string
      override_IsPublish:
        description: 'whether is publishing'
        required: false
        default: "false"
        type: string

    outputs:
      ver_name:
        description: 'parsed or overridden VER_NAME'
        value: ${{ jobs.build.outputs.ver_name }}
      short_sha:
        description: 'short SHA of the run'
        value: ${{ jobs.build.outputs.short_sha }}
      title:
        description: 'parsed or overridden TITLE (Publish only)'
        value: ${{ jobs.build.outputs.title }}
      branch:
        description: 'parsed BRANCH (release only)'
        value: ${{ jobs.build.outputs.branch }}
      prerelease:
        description: 'parsed or overridden PRERELEASE (Publish only)'
        value: ${{ jobs.build.outputs.prerelease }}
      notes:
        description: 'parsed NOTES (Publish only)'
        value: ${{ jobs.build.outputs.notes }}

env:
  APK_OUTPUT_DIR: 'core/app/build/outputs/apk/'
  ARTIFACT_OUTPUT_DIR: 'artifact_output/'

jobs:
  build:
    name: Build ${{ inputs.abi_type }} ${{ inputs.build_type }} APK
    runs-on: ubuntu-latest
    outputs:
      ver_name:  ${{ steps.info.outputs.ver_name }}
      short_sha:  ${{ steps.sha.outputs.short_sha }}
      title:      ${{ steps.info.outputs.title }}
      branch:     ${{ steps.info.outputs.branch }}
      prerelease: ${{ steps.info.outputs.prerelease }}
      notes:      ${{ steps.info.outputs.notes }}

    steps:
    
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          submodules: recursive
          # Only Read The Last 1 Commit
          fetch-depth: 1

      - name: Set Short SHA
        id: sha
        run: echo "short_sha=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Read & Parse RELEASE_INFO
        id: info
        shell: bash
        run: |
          set -euxo pipefail
          INFO_FILE="${{ inputs.override_info_file }}"

          # Exit When File Not Exists Or Is Empty
          if [ ! -s "$INFO_FILE" ]; then
            echo "$INFO_FILE not found or empty"
            exit 1
          fi

          # Set Temp File To Handle shortSHA In INFO_FILE
          TEMP=$(mktemp)
          sed "s/shortSHA/${{ steps.sha.outputs.short_sha }}/g" "$INFO_FILE" > "$TEMP"

          # --------------- Common ---------------
          
          if [ "${{ inputs.override_IsPublish }}" == "true" ]; then
            VER_SUFFIX=""
          elif [ "${{ inputs.build_type }}" == "release" ]; then
            VER_SUFFIX=-dev-"${{ steps.sha.outputs.short_sha }}"
          elif [ "${{ inputs.build_type }}" == "debug" ]; then
            VER_SUFFIX=-devDebug-"${{ steps.sha.outputs.short_sha }}"
          fi
          
          VER_NAME=$(grep '^VER_NAME=' "$TEMP" | cut -d'=' -f2- | tr -d '[:space:]' || true)
          [ -z "$VER_NAME" ] && { echo "VER_NAME missing"; exit 1; }


          # --------------- Publish Only ---------------
          if [ "${{ inputs.override_IsPublish }}" == "true" ]; then
            TITLE=$(grep '^TITLE=' "$TEMP" | cut -d'=' -f2- | sed 's/^[[:space:]]*//;s/[[:space:]]*$//' || true)
            [ -z "$TITLE" ] && TITLE="${VER_NAME} ${{ steps.sha.outputs.short_sha }}"

            PRERELEASE=$(grep '^PRERELEASE=' "$TEMP" | cut -d'=' -f2- | tr -d '[:space:]' || true)
            [ -z "$PRERELEASE" ] && PRERELEASE="true"
            
            BRANCH=$(grep '^BRANCH=' "$TEMP" | cut -d'=' -f2- | tr -d '[:space:]' || true)
            [ -z "$BRANCH" ] && { echo "BRANCH missing or empty"; exit 1; }

            NOTES=$(awk 'BEGIN{f=0} /^NOTES=/{f=1; sub(/^NOTES=/,""); print; next} f' "$TEMP" || true)
            [ -z "$NOTES" ] && { echo "NOTES missing or empty"; exit 1; }

            # Set Params
            echo "title=$TITLE"      >> $GITHUB_OUTPUT
            echo "branch=$BRANCH"    >> $GITHUB_OUTPUT
            echo "prerelease=$PRERELEASE" >> $GITHUB_OUTPUT
            
            # Write File Safely
            echo "notes<<EOF" >> $GITHUB_OUTPUT
            echo "$NOTES"     >> $GITHUB_OUTPUT
            echo "EOF"        >> $GITHUB_OUTPUT
          fi

          echo "ver_name=$VER_NAME"     >> $GITHUB_OUTPUT
          echo "ver_suffix=$VER_SUFFIX" >> $GITHUB_OUTPUT

          # ---------- Print Params ----------
          echo ">>>> RELEASE_INFO parsed:"
          echo "  ver_name : $VER_NAME"
          echo "  ver_suffix: $VER_SUFFIX"
          if [ "${{ inputs.override_IsPublish }}" == "true" ]; then
            echo "  title    : $TITLE"
            echo "  branch   : $BRANCH"
            echo "  prerelease: $PRERELEASE"
            echo "  notes len : $(echo -n "$NOTES" | wc -c)"
          fi

          rm -f "$TEMP"

      # ---------- JDK & Gradle ----------
      - name: Set Up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Restore Gradle Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ~/.gradle/caches/build-cache-*
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*','**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # ---------- Build APK ----------
      - name: Build ${{ inputs.build_type }} APK
        run: |
          ./gradlew :core:app:assemble${{ inputs.build_type }} \
            -PversionSuffix="${{ steps.info.outputs.ver_suffix }}" \
            -PbaseVersion="${{ steps.info.outputs.ver_name }}"

      - name: Show APK_OUTPUT_DIR
        run: ls -laR ${{ env.APK_OUTPUT_DIR }}

      # ---------- Copy & Rename Files----------
      - name: Copy & Rename APK
        run: |
          mkdir -p ${{ env.ARTIFACT_OUTPUT_DIR }}${{ inputs.abi_type }}
          SRC=${{ env.APK_OUTPUT_DIR }}${{ inputs.build_type }}/app-${{ inputs.abi_type }}-${{ inputs.build_type }}.apk
          DST=${{ env.ARTIFACT_OUTPUT_DIR }}${{ inputs.abi_type }}/AndroIDE-${{ inputs.abi_type }}${{ steps.info.outputs.ver_suffix }}.apk
          cp "$SRC" "$DST"
          sha256sum "$DST" > "$DST.sha256"

      - name: Show Artifact Tree
        run: ls -laR ${{ env.ARTIFACT_OUTPUT_DIR }}

      # ---------- Upload Files ----------
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: AndroIDE-${{ inputs.abi_type }}${{ steps.info.outputs.ver_suffix }}
          path: ${{ env.ARTIFACT_OUTPUT_DIR }}${{ inputs.abi_type }}/*

      - name: Upload Mapping (release only, not debug)
        if: ${{ inputs.build_type == 'release' }}
        uses: actions/upload-artifact@v4
        with:
          name: release-mappings-${{ steps.sha.outputs.short_sha }}
          path: '**/build/outputs/mapping'

