name: Build APK

on:
  push:
    #branches: [ "master", "main" ]
    paths-ignore:
      - '**.md'
      - 'RELEASE_INFO'
      - 'fastlane/**'
      - '.github/workflows/*.yml'
  workflow_dispatch: {}

# Cancel old runs
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build_matrix:
    strategy:
      fail-fast: false
      matrix:
        abi_type: ['arm64-v8a']
        #abi_type: ['arm64-v8a', 'armeabi-v7a', 'x86_64']
        build_type: ['release']
        #build_type: ['release', 'debug']
    uses: ./.github/workflows/_build-apk-reusable.yml
    with:
      build_type: ${{ matrix.build_type }}
      abi_type:   ${{ matrix.abi_type }}
      # Other params read by _build-apk-reusable.yml

